events {}

http {
  upstream flash_sale_backend {
    server host.docker.internal:3000;
    server host.docker.internal:3001;

    keepalive 64;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://flash_sale_backend;

      proxy_http_version 1.1;
      proxy_set_header Connection "";

      add_header X-Upstream-Addr $upstream_addr;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}